### ISSUE TITLE
Materialize functions within functions

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#196]
Currently:

```elm
func lag_day x = s"lag_day_todo({x})"
func ret x = x / (lag_day x) - 1 + dividend_return

from a
select (ret b)
```

materializes the select as:

```yaml
- Select:
    - Items:
        - Terms:
            - Ident: b
            - Raw: /
            - Items:
                - Terms:
                    - Ident: lag_day      # <- Doesn't run the function
                    - Ident: b
            - Raw: "-"
            - Raw: "1"
            - Raw: +
            - Ident: dividend_return
```

We should fix!
