### ISSUE TITLE
s-string with double braces outputs extra braces

### ISSUE THREAD

**Issue by echou** [PRQL/prql#3151]
### PRQL input

```elm
from foo
derive b =  s"""
    concat('{{', {a}, '}}')
"""
```

### SQL output

```SQL
SELECT
  *,
  concat('{', { a }, '}') AS b
FROM
  foo

-- Generated by PRQL compiler version:0.9.2 (https://prql-lang.org)
```

### Expected SQL output

```SQL
SELECT
  *,
  concat('{', a, '}') AS b
FROM
  foo
```

### MVCE confirmation

- [ ] Minimal example
- [ ] New issue

**Comment by max-sixty** [comment]
Thanks, nice report @echou .

---

It looks like the parser isn't skipping over the double `{{` correctly. From the `pl` from the playground:

```yaml
              - SString:
                  - String: |2-  # ignore, awkward yaml display
                      
                          concat('
                  - String: "{', {a}, '}"  # here
                  - String: |
                      ')
                alias: b
```

`"{', {a}, '}"` should instead know that `a` is an expr.

Compare with the s-string in

```sql
from foo
derive b =  s"""
    concat({a})
"""
```

```yaml
                - String: |2-
                    
                        concat(
                - Expr:  # Here's an actual Expr! Not a string
                    expr:
                      kind:
                        ColumnRef: 0
                      span: null
                    format: null
                - String: |
                    )
```

This might be a reasonable first / early issue — the context is limited to `prql-parser`, so doesn't require traipsing through the whole compiler. Chumsky is a small learning bump, but very nice after that bump.
