### ISSUE TITLE
Integration tests for BigQuery with the `bigquery-emulator`

### ISSUE THREAD

**Issue by eitsupi** [PRQL/prql#3607]
Related to #872.

I read a bit of the documentation as I found out about <https://github.com/goccy/bigquery-emulator>, but it looks very useful for uses like this repository.
We may need to think a bit about how to load data from CSV files.

**Comment by eitsupi** [comment]
I tried this and found it very difficult to load data.

**Comment by eitsupi** [comment]
For anyone who wants to try this.

I can get the container to work with the following compose file, but I can't seem to figure out how to load the CSV file into the database, I can't seem to load the CSV file from the GCS using SQL (Maybe I'm missing something).

```yml
  bigquery:
    image: ghcr.io/goccy/bigquery-emulator:latest
    platform: linux/amd64
    ports:
      - "9050:9050"
    environment:
      STORAGE_EMULATOR_HOST: http://gcs:4443
    command: --project=test
  gcs:
    image: fsouza/fake-gcs-server:1
    expose:
      - 4443
    volumes:
      - ./data/chinook:/data:ro
    command: -scheme http
```
