### ISSUE TITLE
Select columns collection is inaccurate

### ISSUE THREAD

**Issue by hetian9288** [PRQL/prql#4829]
## Problem Description
PRQL
```
from employees
select {id, name}
```
RQ:
```
def:
  version: null
  other: {}
tables:
  - id: 0
    name: null
    relation:
      kind:
        ExternRef:
          LocalTable:
            - employees
      columns:
        - Single: id
        - Single: name
        - Wildcard
relation:
        ...
```
In addition to the id and name I selected, columns also include Wildcard

## Expected goal
I hope that columns only collect the id and name I defined

**Comment by max-sixty** [comment]
The full RQ from this is:

```yaml
def:
  version: null
  other: {}
tables:
  - id: 0
    name: null
    relation:
      kind:
        ExternRef:
          LocalTable:
            - employees
      columns:
        - Single: id
        - Single: name
        - Wildcard
relation:
  kind:
    Pipeline:
      - From:
          source: 0
          columns:
            - - Single: id
              - 0
            - - Single: name
              - 1
            - - Wildcard
              - 2
          name: employees
      - Select:
          - 0
          - 1
      - Select:
          - 0
          - 1
  columns:
    - Single: id
    - Single: name

```

The columns from the relation are indeed just `id` & `name`.

The columns from the _table_ are all columns — it works out that there is `id` & `name`, and then has a wildcard for the others. Only the two named columns are then selected.

Does that make sense?

(Possibly it could be clearer — e.g. why are there two `select`s in the pipeline — but I don't think it's wrong...)
